import './index.scss'
export { default as Icon } from './icon/icon'
export { default as Button } from './button/button'
export { default as Form } from './form/form'
export { ValidateFields } from './form/form'
export { default as Input } from './input/input'
export { default as Layout } from './layout/layout'
export { Header } from './layout/layout'
export { Footer } from './layout/layout'
export { Content } from './layout/layout'
export { Aside } from './layout/layout'
export { default as Modal } from './modal/modal'
export { confirm } from './modal/modal'
export { alert } from './modal/modal'
export { default as Switch } from './switch/switch'

